/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package nba_selenium;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
  String[] resultsKobeBryant = {"2015-16 7.1", "2014-15 5.3", "2013-14 2.7", "2012-13 5.2",
      "2011-12 4.9", "2010-11 4.3", "2009-10 4.1", "2008-09 4.1", "2007-08 5.1", "2006-07 5.2", "2005-06 6.5",
      "2004-05 5.9", "2003-04 3.3", "2002-03 4.0", "2001-02 1.7", "2000-01 2.9", "1999-00 2.2", "1998-99 2.0",
      "1997-98 2.8", "1996-97 1.9" };
  String[] resultsLukaDoncic = {"2022-23 8.8", "2021-22 8.8", "2020-21 8.3", "2019-20 8.9",
      "2018-19 7.1" };

  @Test
  void testWebdriver() {
    App scraper = new App();
    assertNotNull(scraper.createFirefoxDriver(), "WebDriver is null");
  }
  void testUrlFormatter() {
    App scraper = new App();
    assertEquals(
        "https://www.nba.com/stats/players/traditional?CF=PLAYER_NAME*E*Luka Doncic&PerMode=Totals&Season=2021-22&dir=-1&sort=PTS",
        scraper.formatUrl("Luka Doncic", "2021-22"), "Url formatter works incorrectly");
  }
  void testForKobe() {
    App scraper = new App();
    assertArrayEquals(resultsKobeBryant, scraper.getData("Kobe Bryant"), "incorrect result for Kobe Bryant");
  }
  void testForDoncic() {
    App scraper = new App();
    assertArrayEquals(resultsLukaDoncic, scraper.getData("Luka Doncic"), "incorrect result for Luka Doncic");
  }
}
